### PR TITLE
support ida7.3

### PR DESCRIPTION
**Pull request by wnxd**

### CODE REVIEW

**Comment by RolfRolles** [comment]
Sorry, but what exactly is this commit? It says "fix bug" and instead adds a 275-line .cpp file with no comments in it.

Perhaps the biggest reason I released this code -- even more than wanting to release a plugin with specific features -- was so that other people could see how I'd used the microcode API while unpacking this sample. I tried to accomplish this by releasing heavily-commented source code. This commit apparently adds a bunch of functionality with no description of what that functionality is, and no comments. 

I, the author, do not know what this commit does and I am inclined not to accept a pull request that I do not know what it does, and which has no comments.

**Comment by wnxd** [comment]
The first commit is valid.

**Comment by wnxd** [comment]
<RestoreMacroCompression> is restore compression code (LLVM Macro Compression)
E.g: facebook, fgo?

**Comment by RolfRolles** [comment]
Okay. For the sample I used in the [original blog entry](http://www.hexblog.com/?p=1248), does it make use of macro compression?

**Comment by RolfRolles** [comment]
Okay, I have cherry picked your commit for adding support for IDA 7.3. Thank you for that. Beyond that, though, this project has a very specific purpose: to break the obfuscating compiler in the [original blog entry](http://www.hexblog.com/?p=1248), and do using clean, well-documented code. Your pull request has nothing to do with the obfuscating compiler in the original blog entry, therefore it has no place in this repository. Therefore I am rejecting the rest of this pull request.

I hope you keep developing the code, though, and that you make it available to the community. It's a good thing that you're doing, however I am unwilling to take on maintaining code that I did not write, and that has nothing to do with my own project. I would recommend creating your own repository to house this project, or forking mine, or whatever you want to do -- anything but pushing it into my repository.

**Comment by RolfRolles** [comment]
I took a look at your project and it's pretty cool. In summary, it seems like you (recursively) inline every "sub_" or "loc_" function with a single return site into the caller. Although there are a few things I don't fully understand (only having taken a brief look at your code), I can offer you a few suggestions for improvement:

`is_sub():`

* See if `name.hpp::dummy_name_ea()` does what you want here.

`get_mop():`

* `intel.hpp` defines the `RegNo` enum, with numeric constants such as `R_ax`, `R_cx`, etc. These are not the same constants that Hex-Rays uses internally for microregister numbers (and furthermore, they are not defined directly in IDAPython AFAIK), but you can convert between them using `hexrays.hpp::reg2mreg`. Here's a snippet from my recent (IDAPython) project:

````
    IDA_RCX_REGNUM = 0x01
    IDA_RDX_REGNUM = 0x02
    # ...

    rcxMreg = ida_hexrays.reg2mreg(IDA_RCX_REGNUM)
    rdxMreg = ida_hexrays.reg2mreg(IDA_RDX_REGNUM)
    # ...

    rcxMop  = ida_hexrays.mop_t(rcxMreg, 8)
    rdxMop  = ida_hexrays.mop_t(rdxMreg, 8)
    # ...
````

In this case, you'd want to use `R_sp` (`0x04`) here, which will be the same for 32- and 64-bit (i.e., `ESP` and `RSP` both correspond to the register number `0x04`).

**Comment by wnxd** [comment]
Thank you for your help.

is_sub(): Is used to determine non-external library functions

**Comment by wnxd** [comment]
`intel.hpp` defines the `RegNo` enum, `R_sp = 4`
but `mreg2reg(get_mop("sp", 8), 8) = 161`

**Comment by wnxd** [comment]
I need an x64 hook library (variable arguments function), is there a recommendation?
Hook `hexdsp` to intercept the `gen_microcode` operation.

**Comment by RolfRolles** [comment]
> `intel.hpp` defines the `RegNo` enum, `R_sp = 4`
> but `mreg2reg(get_mop("sp", 8), 8) = 161`

Since you didn't paste any code, I can't tell exactly what went wrong for you, but it does work. Here's a small IDAPython script illustrating:
````
IDA_RSP_REGNUM = 0x04
rspMreg = ida_hexrays.reg2mreg(IDA_RSP_REGNUM)
rspMop  = ida_hexrays.mop_t(rspMreg, 8)
print "R_sp: %#x, reg2mreg(%#x) = %#x, mop.r = %#x, mreg2reg(%#x,8) = %#x" % (IDA_RSP_REGNUM, IDA_RSP_REGNUM, rspMreg, rspMop.r, rspMop.r, ida_hexrays.mreg2reg(rspMop.r,8))
````

This produces the output: `R_sp: 0x4, reg2mreg(0x4) = 0x28, mop.r = 0x28, mreg2reg(0x28,8) = 0x4`.

> I need an x64 hook library (variable arguments function), is there a recommendation?
> Hook `hexdsp` to intercept the `gen_microcode` operation.

Don't, is my recommendation. Either make use of the existing hooking mechanisms, or identify some way in which the existing mechanisms are insufficient and put in a feature request. Be sure to put sufficient effort into reviewing and experimenting with the existing hooking mechanisms before issuing a feature request.

**Pull request closed without merging**
